/*
* generated by Xtext
*/
package ac.soton.xtext.statemachine.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import ac.soton.xtext.statemachine.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {
	
	@Inject
	private DslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected ac.soton.xtext.statemachine.ui.contentassist.antlr.internal.InternalDslParser createParser() {
		ac.soton.xtext.statemachine.ui.contentassist.antlr.internal.InternalDslParser result = new ac.soton.xtext.statemachine.ui.contentassist.antlr.internal.InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractNodeAccess().getAlternatives(), "rule__AbstractNode__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getStateMachineAccess().getGroup(), "rule__StateMachine__Group__0");
					put(grammarAccess.getStateMachineAccess().getGroup_3(), "rule__StateMachine__Group_3__0");
					put(grammarAccess.getStateMachineAccess().getGroup_3_2(), "rule__StateMachine__Group_3_2__0");
					put(grammarAccess.getStateMachineAccess().getGroup_4(), "rule__StateMachine__Group_4__0");
					put(grammarAccess.getStateMachineAccess().getGroup_4_2(), "rule__StateMachine__Group_4_2__0");
					put(grammarAccess.getStateMachineAccess().getGroup_5(), "rule__StateMachine__Group_5__0");
					put(grammarAccess.getStateMachineAccess().getGroup_5_2(), "rule__StateMachine__Group_5_2__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup_2(), "rule__Transition__Group_2__0");
					put(grammarAccess.getTransitionAccess().getGroup_3(), "rule__Transition__Group_3__0");
					put(grammarAccess.getTransitionAccess().getGroup_4(), "rule__Transition__Group_4__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getStateAccess().getGroup_3(), "rule__State__Group_3__0");
					put(grammarAccess.getInitialAccess().getGroup(), "rule__Initial__Group__0");
					put(grammarAccess.getJunctionAccess().getGroup(), "rule__Junction__Group__0");
					put(grammarAccess.getForkAccess().getGroup(), "rule__Fork__Group__0");
					put(grammarAccess.getJoinAccess().getGroup(), "rule__Join__Group__0");
					put(grammarAccess.getAnyAccess().getGroup(), "rule__Any__Group__0");
					put(grammarAccess.getFinalAccess().getGroup(), "rule__Final__Group__0");
					put(grammarAccess.getStateMachineAccess().getNameAssignment_2(), "rule__StateMachine__NameAssignment_2");
					put(grammarAccess.getStateMachineAccess().getNodesAssignment_3_1(), "rule__StateMachine__NodesAssignment_3_1");
					put(grammarAccess.getStateMachineAccess().getNodesAssignment_3_2_1(), "rule__StateMachine__NodesAssignment_3_2_1");
					put(grammarAccess.getStateMachineAccess().getTransitionsAssignment_4_1(), "rule__StateMachine__TransitionsAssignment_4_1");
					put(grammarAccess.getStateMachineAccess().getTransitionsAssignment_4_2_1(), "rule__StateMachine__TransitionsAssignment_4_2_1");
					put(grammarAccess.getStateMachineAccess().getStateMachinesAssignment_5_1(), "rule__StateMachine__StateMachinesAssignment_5_1");
					put(grammarAccess.getStateMachineAccess().getStateMachinesAssignment_5_2_1(), "rule__StateMachine__StateMachinesAssignment_5_2_1");
					put(grammarAccess.getTransitionAccess().getEventAssignment_2_1(), "rule__Transition__EventAssignment_2_1");
					put(grammarAccess.getTransitionAccess().getSourceAssignment_3_1(), "rule__Transition__SourceAssignment_3_1");
					put(grammarAccess.getTransitionAccess().getTargetAssignment_4_1(), "rule__Transition__TargetAssignment_4_1");
					put(grammarAccess.getStateAccess().getNameAssignment_2(), "rule__State__NameAssignment_2");
					put(grammarAccess.getStateAccess().getNestedAssignment_3_1(), "rule__State__NestedAssignment_3_1");
					put(grammarAccess.getInitialAccess().getNameAssignment_2(), "rule__Initial__NameAssignment_2");
					put(grammarAccess.getJunctionAccess().getNameAssignment_2(), "rule__Junction__NameAssignment_2");
					put(grammarAccess.getForkAccess().getNameAssignment_2(), "rule__Fork__NameAssignment_2");
					put(grammarAccess.getJoinAccess().getNameAssignment_2(), "rule__Join__NameAssignment_2");
					put(grammarAccess.getAnyAccess().getNameAssignment_2(), "rule__Any__NameAssignment_2");
					put(grammarAccess.getFinalAccess().getNameAssignment_2(), "rule__Final__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			ac.soton.xtext.statemachine.ui.contentassist.antlr.internal.InternalDslParser typedParser = (ac.soton.xtext.statemachine.ui.contentassist.antlr.internal.InternalDslParser) parser;
			typedParser.entryRuleStateMachine();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
