/*
 * generated by Xtext
 */
package ac.soton.xtext;

import org.eclipse.xtext.parsetree.reconstr.ICommentAssociater;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ContextDslRuntimeModule extends ac.soton.xtext.AbstractContextDslRuntimeModule {
	
	
}
