/*
* generated by Xtext
*/
package ac.soton.uk.iumlb.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ac.soton.uk.iumlb.xtext.ui.internal.DslActivator.getInstance().getInjector("ac.soton.uk.iumlb.xtext.Dsl");
	}
	
}
