<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decomposition" nsURI="http://soton.ac.uk/models/eventb/decomposition/2016"
    nsPrefix="decomposition">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRegion" abstract="true" eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ready" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedVariables" upperBound="-1"
        eType="ecore:EClass ../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedExtensions" upperBound="-1"
        eType="ecore:EClass ../../org.eventb.emf.core/model/eventbcore.ecore#//AbstractExtension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="../../org.eventb.emf.core/model/eventbcore.ecore#//EventBNamedCommentedElement #//AbstractRegion ../../org.eventb.emf.core/model/eventbcore.ecore#//AbstractExtension">
    <eAnnotations source="org.eventb.emf.core.extendedMetaClasses" references="../../org.eventb.emf.core/model/eventbcore.ecore#//machine/Machine"/>
  </eClassifiers>
</ecore:EPackage>
