/*
* generated by Xtext
*/
package ac.soton.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ContextDslStandaloneSetup extends ContextDslStandaloneSetupGenerated{

	public static void doSetup() {
		new ContextDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

