/*
 * generated by Xtext
 */
package ac.soton.uk.iumlb.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DslUiModule extends ac.soton.uk.iumlb.xtext.ui.AbstractDslUiModule {
	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
